create table client
(
    id                 bigint generated by default as identity primary key,
    short_name         text not null,
    long_name          text not null,
    address            text not null,
    address2           text,
    address3           text,
    postal_code        text not null,
    city               text not null,
    country            text not null,
    email              text,
    phone_num          text,
    phone_num2         text,
    phone_num3         text
);

